name: electrocom
description: A modern employee management mobile app for Android and iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  table_calendar: ^3.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  path: ^1.9.0
  file_picker: ^8.1.6
  flutter_image_compress: ^2.3.0
  photo_view: ^0.15.0
  syncfusion_flutter_pdfviewer: ^27.2.5
  uuid: ^4.5.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
