name: electrocom
description: A modern employee management mobile app for Android and iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.0
  google_fonts: ^6.0.0
<<<<<<< HEAD
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
=======
  intl: ^0.18.0
>>>>>>> ae44b1d8baa673d2cb9315f57d94081e1af05f12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
